### ISSUE TITLE
你好，readme可以详细一点么，没有使用过qt5的开发，这个项目应该如何启动呢

### ISSUE THREAD

**Issue by pwan5** [Gaoyifei1011/AmapProgram#1]

**Comment by Gaoyifei1011** [comment]
您好，感谢您(mengyujun)的提问
抱歉，这个github由于服务器在国外以及一些其他的问题吧，经常会发生有时候就能打开有时候就无法访问情况，困扰了我很长时间
关于这个项目的readme目前还没有说明完整，我会尽快在网络良好下继续完善的，之后会附上截图
这个项目建议使用pycharm打开，我本人就是使用pycharm编写的，根目录下有一个main.py，这个文件就是程序的入口

**Comment by pwan5** [comment]
哈哈 太客气了
我是clone之后，按照完成依赖之后，直接运行pyhton main.py 出现了一些问题 
希望可以看到比较详细的readme以及截图
非常感谢

**Comment by Gaoyifei1011** [comment]
今天上午我已经完善了readme.md文档的内容了，你可以参考一下，如果遇到问题建议贴图说明一下出错的原因。

**Comment by pwan5** [comment]
> 今天上午我已经完善了readme.md文档的内容了，你可以参考一下，如果遇到问题建议贴图说明一下出错的原因。

感谢！ 非常详细，很认真很棒
